DROP DATABASE IF EXISTS `posts`;
CREATE DATABASE `posts`;
USE `posts`;

CREATE TABLE `cards`(
	`id` int AUTO_INCREMENT PRIMARY KEY,
	`title` VARCHAR(50) NOT NULL,
	`body` LONGTEXT NOT NULL,
	`date` DATE NOT NULL
);